### ISSUE TITLE
Dataset: Water Vapour

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#1009]
Water Vapour data is available:
https://catalogue.ceda.ac.uk/uuid/4a85c0ef880e4f668cd4ec8e846855ef

> The data is for Total Column Water Vapour over land, and there are 4 different products (0.05 and 0.5 degree at monthly and daily resolution).

Let's go for the monthly time data set.
And the high spatial resolution.

Color scale: tbd.

**Comment by pwambach** [comment]
closing, see https://github.com/ubilabs/esa-climate-from-space/issues/1091
