### ISSUE TITLE
Show colored base map when no data is available

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#1051]
- [x] Use this coilored basemap Colored Basemap: https://ubilabs.slack.com/archives/CFBKYU8D9/p1646305896145369
˜˜- [ ] Add an attribution for this dataset for 'Planetary Vision' (lets talk if this is not very easy)˜˜

**Comment by pwambach** [comment]
New basemap tiles have been generated and uploaded. But I'm not sure about the attribution task. Where and why? We don't have attributions for the other basemaps

**Comment by pwambach** [comment]
![Screenshot 2022-03-03 at 15 53 44](https://user-images.githubusercontent.com/1611635/156589490-0a0e48ae-3e77-470d-820d-89910fa9221f.png)
