### ISSUE TITLE
Story Mapper: cannot upload file. Throws an error

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#1078]
I tried to upload the file online (https://europe-west3-esa-climate-from-space.cloudfunctions.net/storyMapper)

If I run it locally I get the following error:

<img width="931" alt="image" src="https://user-images.githubusercontent.com/2733607/158759254-d7ac4ce8-4c65-4c72-8402-4ec29ff350b7.png">

The new content file:
[data-layer-descriptions (1).xlsx](https://github.com/ubilabs/esa-climate-from-space/files/8282337/data-layer-descriptions.1.xlsx)

**Comment by KatvonRivia** [comment]
memory limit was exceeded, should work now
