### ISSUE TITLE
BUG: app crashes in dutch

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#1099]
Version 1.5 crashes when language is set to dutch:

https://storage.googleapis.com/esa-cfs-versions/web/1.5.0/index.html#/?lng=nl

It works in all other languages:
https://storage.googleapis.com/esa-cfs-versions/web/1.5.0/index.html#/?lng=de
https://storage.googleapis.com/esa-cfs-versions/web/1.5.0/index.html#/?lng=en
https://storage.googleapis.com/esa-cfs-versions/web/1.5.0/index.html#/?lng=fr
https://storage.googleapis.com/esa-cfs-versions/web/1.5.0/index.html#/?lng=es

**Comment by pwambach** [comment]
https://github.com/ubilabs/esa-climate-story-mapper/pull/17

**Comment by pwambach** [comment]
The bug was caused because the input sheet was not valid. We now check the layer schema and abort with an error in case it doesn't match
