### ISSUE TITLE
Videos not running (MacOS Safari)

### ISSUE THREAD

**Issue by annikabock** [ubilabs/esa-climate-from-space#1321]
All the interview videos give an error message on Mac Safari (in Carbon Cycle, Planetary Heat Pumps, Biodiversity, Coasts Under Threat). But these files play back fine on Mac Firefox. All other videos play back fine on both. Maybe it’s a simple thing like case sensitivity in the file names, or please let me know if you need the interview videos in a different format?

**Comment by Immo-Be** [comment]
We are missing a specific video file with a resolution of 720p for the interviews of these stories. We generate the URL of the video asset based on the screen resolution and expect to have four different videos on GCP available. It would be best to make sure that the missing videos are uploaded to the cloud storage. @annikabock

**Comment by annikabock** [comment]
@Immo-Be 
You can find the missing HD720 video files for the interviews here:

http://www.planetaryvisions.com/download.php?id=7

Please let me know if there you have any problem downloading or using them.

**Comment by Immo-Be** [comment]
Cool, this works. Thanks :) The videos will be only with the next release
