### ISSUE TITLE
some corrections to the German translation of the data layer descriptions

### ISSUE THREAD

**Issue by annikabock** [ubilabs/esa-climate-from-space#1324]
Die Excel Datei von Philip könnt ihr hier direkt hochladen:

https://europe-west3-esa-climate-from-space.cloudfunctions.net/storyMapper

Dann gibt es einen PR und die Inhalte sind direkt auf development verfügbar: https://storage.googleapis.com/esa-cfs-versions/web/develop/index.html#/
Ich habe die Excel Datei immer im [Sharepoint abgelegt](https://brockmannconsult.sharepoint.com/sites/KnowledgeExchange/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FKnowledgeExchange%2FShared%20Documents%2FPhases%5F1%2D3%2FWP2000%20%2D%20Climate%20from%20Space%2FCfS%20Data%20Layers&viewid=68bc9942%2Dbe99%2D47d0%2D98d7%2D370546579de1).

[data-layer-descriptions-3-translated-checked.xlsx](https://github.com/ubilabs/esa-climate-from-space/files/13737115/data-layer-descriptions-3-translated-checked.xlsx)

**Comment by andreashelms** [comment]
Already done with https://github.com/ubilabs/esa-climate-from-space/pull/1305

**Comment by annikabock** [comment]
neeew file. was an missing update on PEs side



[data-layer-descriptions-3-translated-checked (1).xlsx](https://github.com/ubilabs/esa-climate-from-space/files/13857708/data-layer-descriptions-3-translated-checked.1.xlsx)

@andreashelms
