### ISSUE TITLE
When sharing the App with URL parameter, the globe only renders after interaction

### ISSUE THREAD

**Issue by annikabock** [ubilabs/esa-climate-from-space#1329]
1. Click this link: https://storage.googleapis.com/esa-cfs-versions/web/develop/index.html#/?globe=SI13.54I14.57I575843I0.00I1685702481032I0II
2. globe stays black
3. zoom out --> globe appears

**Comment by usefulthink** [comment]
this seems to be fixed. Can we close this @annikabock?

**Comment by annikabock** [comment]
Thanks @usefulthink looks good to me
