### ISSUE TITLE
new animations

### ISSUE THREAD

**Issue by annikabock** [ubilabs/esa-climate-from-space#1340]
We have new material for CfS in the form of the phase 4 and 5 animations:

http://www.planetaryvisions.com/download.php?id=7
videos-for-internal-player-3.zip

Two of the animations go in existing stories:
paris agreement —> 32 Welcome to Climate from Space 
land ice dynamics —> 21 Water Cycle

I’ve attached the updated story files, and also uploaded them to the narratives folder on the sharepoint:

https://brockmannconsult.sharepoint.com/sites/KnowledgeExchange/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FKnowledgeExchange%2FShared%20Documents%2FPhases%5F1%2D3%2FWP2000%20%2D%20Climate%20from%20Space%2FNarratives&viewid=68bc9942%2Dbe99%2D47d0%2D98d7%2D370546579de1

The remaining two animations go in new stories (also attached and uploaded):
Story 42 Coastal Sea Level (keywords: sea level) story pin location 80.21W, 25.78N
Story 43 El Nino 2023 (keywords: sea surface temperature, sea surface salinity, cloud) story pin location 120W, 0N

If you could please add the new videos and stories to the development version, I can check them and use the Story Mapper to update any fixes. (The updates and new stories are English-language only for now. We’ll translate along with the wider text updates in due course.)

**Comment by Immo-Be** [comment]
@annikabock I think only you and Patric have access to the sharepoint. Could you send me the contents of the mentioned folder?

**Comment by annikabock** [comment]
surrrre

[OneDrive_1_05-02-2024.zip](https://github.com/ubilabs/esa-climate-from-space/files/14165090/OneDrive_1_05-02-2024.zip)

**Comment by Immo-Be** [comment]
@annikabock Die Stories 32 und 21 sind angepasst, die neuen Stories 42 und 43 sind nun in GCP hochgeladen (und damit in Storymapper verfügbar)
