### ISSUE TITLE
Co2 - replace existing layer

### ISSUE THREAD

**Issue by annikabock** [ubilabs/esa-climate-from-space#1370]
https://catalogue.ceda.ac.uk/uuid/2c1cb1d606c4421e9339a3028839a41f

Das Datenformat ist ähnlich. Die Daten sind vom OCO-2 Satelliten, der im Vergleich zum TROPOMI Instrument auf S5P ein viel

kleine swath width (Spur- oder Abdeckbreite) hat, namlich nur 10 km Breite entlang des Satellitenorbits, im Vgl. zu 2600 km bei TROPOM.

Siehe zB:

https://ocov2.jpl.nasa.gov/galleries/data-products/#images-12

oder

https://acp.copernicus.org/articles/19/9371/2019/#&gid=1&pid=1
Die Abdeckung ist also viel schlechte als beim Methan-Produkt.

**Comment by annikabock** [comment]
Blocked - I requested the gridded data from Michael

**Comment by annikabock** [comment]
der CO2 Datensatz ist fertig:

https://nc.uni-bremen.de/index.php/s/sAMoDfxXxC4SWd8
(1 file, [l2db_oco2_focal_co2_v11_slimco2_2024_25.nc](http://l2db_oco2_focal_co2_v11_slimco2_2024_25.nc/), 17 MB)

Monatlich, 2.5°x2.5° mit mindestens 25 observations pro gridbox.
Anderes Format und niedrigere Auflösung als Methan-Daten, da OCO-2 räumlich sehr sparse mit nur 10 km swath width (mit 8 ground pixel) im Vergleich zu TROPOMI/S5P mit 2600 km swath.

Nur mit niedrigerer Auflösung kriegt man die Karten einigermassen gefüllt. Trotzdem noch viele Lücken.

**Comment by Immo-Be** [comment]
@pmast Wir haben den C02 Layer aktualisiert, haben aber keine Infos zu den Metadaten des neuen Datensatzes. Kannst du uns da helfen?

**Comment by Immo-Be** [comment]
Was ich meine, sind die Infos bzw. `descriptions` zu den Layern, die in den `layers-[lang].json` definiert sind und dann z.b. hier eingebunden: https://cfs.climate.esa.int/index.html#/?globe=SI2.33I14.42I23840000I0.00I1042675200000I0Igreenhouse.xco2I

Den Datensatz findest du hier: https://catalogue.ceda.ac.uk/uuid/2c1cb1d606c4421e9339a3028839a41f

**Comment by pmast** [comment]
The `layers` file only gives you name, description etc.

```
description:  "[…]",
id: "greenhouse.xco2",
name: "Kohlendioxid (CO2)",
shortName: "Kohlendioxid (CO2)",
type: "Atmospheric Composition",
usageInfo: "© ESA"
```
Except for ID and description, take the ones listed here.

The long text in the **descriptions** part comes from the science leads.
The numeric part also comes from the science leads or is collected from the [dataset's ODP](https://catalogue.ceda.ac.uk/uuid/2c1cb1d606c4421e9339a3028839a41f/) website.

The values above are all set in [this spreadsheet](https://brockmannconsult.sharepoint.com/:x:/r/sites/KnowledgeExchange/_layouts/15/Doc.aspx?sourcedoc=%7B961DE2B7-9A97-48D5-BB3E-106A5C43484F%7D&file=data-layer-descriptions-3-translated-checked-updated-ubi.xlsx&action=default&mobileredirect=true) and then uploaded via the [story mapper](https://europe-west3-esa-climate-from-space.cloudfunctions.net/storyMapper)

---

There is a metadata file with more information:

```
basemap: null,
id: "greenhouse.xco2",
legendValues: ["400 ppm", "395", "390", "385", "380", "375", "370", "365"],
maxValue: 0.0004179562965873629,
minValue: 0.0003599192132242024,
timeFormat: {year: "numeric", month: "long"},
timestamps: ["2003-01-16T00:00:00Z", "2003-02-15T00:00:00Z", "2003-03-16T00:00:00Z", "2003-04-16T00:00:00Z",…],
type: "image",
units: "",
version: "1.14.1",
zoomLevels: 3
```

Those value are specified in the rendering process

**Comment by andreashelms** [comment]
Hallo Patrick,

mein Kollege Max Reuter, der die Daten erzeugt hat, ist in CC. Ich bin morgen noch im Büro, dann erst wieder 7.10.2024. Ev. kann Max Fragen in dieser Zeit dann beantworten.
Hier meine Kommentare:
Animation: Alles rot ! Die Farbskale muss angepasst werden. Derzeit ist sie unbrauchbar :-(
Letzten Satz bitte ersetzen: Korrekt ist:

Die CCI-Karten basieren auf den Daten des Spektrometers Orbiting Carbon Observatory-2 (OCO-2) der NASA. Die OCO-2 CO2 Daten wurden mittels des FOCAL-Algorithmus (Version 11) erzeugt, welcher von der Universität Bremen entwickelt wurde.

Hier die korrekten Daten:
Zeitspanne: Januar 2015 - Dezember 2023
Zeitliche Auflösung: monatlich
Räumliche Ausdehnung: global
Geografische Auflösung: 2,5° x 2,5°
Version: 11
DOI: 10.3390/rs9111102
Finanzierung: ESA CCI.
Anmerkung: Reuter, M., M. Buchwitz, O. Schneising, S. Noel, H. Bovensmann, J. P. Burrows, A Fast Atmospheric Trace Gas Retrieval for Hyperspectral Instruments Approximating Multiple Scattering - Part 2: Application to XCO2 Retrievals from OCO-2, Remote Sens., 9, 1102, doi:10.3390/rs9111102, 2017.

Michael
