### ISSUE TITLE
evaluate fire data sets

### ISSUE THREAD

**Issue by annikabock** [ubilabs/esa-climate-from-space#1371]
please check if one can merge
the existing data set
https://catalogue.ceda.ac.uk/uuid/3628cb2fdba443588155e15dee8e5352

with one of these two newer ones
https://catalogue.ceda.ac.uk/uuid/da8e669a74334c82a56e0b470bc4ef04 (grid product)
https://catalogue.ceda.ac.uk/uuid/d441079fc77f49fabeb41330612b252f (pixel product)

**Comment by yfr** [comment]
The comes from different satellites. And the date ranges overlap. We could, technically, overwrite the old data with the newer one.  But since the data comes from different sources, it is also differnt data in general. 

So technically yes, scientifically unsure.
