### ISSUE TITLE
image for stories gallery

### ISSUE THREAD

**Issue by annikabock** [ubilabs/esa-climate-from-space#1463]
something like this?

![Image](https://github.com/ubilabs/esa-climate-from-space/assets/8329219/ac91d5e7-c52f-4556-9e04-e71d50830f2c)

**Comment by elenamuxui** [comment]
![Image](https://github.com/ubilabs/esa-climate-from-space/assets/63637901/7c03e1b1-3994-4120-9492-73ce760605d0)
![Image](https://github.com/ubilabs/esa-climate-from-space/assets/63637901/12842711-6d02-4c42-a06f-da38d911ec0e)
