### ISSUE TITLE
buttons to jump inbetween main story and subchapters

### ISSUE THREAD

**Issue by annikabock** [ubilabs/esa-climate-from-space#1506]
Button Text:
Select a Methane Giant

**Comment by elenamuxui** [comment]
<img width="335" alt="Bildschirmfoto 2024-05-23 um 12 54 42" src="https://github.com/ubilabs/esa-climate-from-space/assets/63637901/425c11d1-6e5a-445b-96ec-4d04dc6bb949">


<img width="346" alt="Bildschirmfoto 2024-05-23 um 12 54 47" src="https://github.com/ubilabs/esa-climate-from-space/assets/63637901/3823b16a-f99c-4167-8c97-ae2aa87adace">

**Comment by annikabock** [comment]
will do differently
