### ISSUE TITLE
River discharge data set

### ISSUE THREAD

**Issue by annikabock** [ubilabs/esa-climate-from-space#1604]
https://catalogue.ceda.ac.uk/uuid/c5f0aa806ec444b4a4209b49efc4bb65

maybe display data like this?
https://www.esa.int/ESA_Multimedia/Videos/2023/10/Antarctic_ice_shelf_demise

**Comment by annikabock** [comment]
Text CO2
Kohlenstoffdioxid (CO2) ist das wichtigste anthropogene Treibhausgas. Ein gutes Verständnis der CO2-Quellen und -Senken ist wichtig, um unser zukünftiges Klima zuverlässig vorherzusagen. Globale Satellitendaten helfen dabei und tragen somit zur Verbesserung der Klimavorhersagen bei. Wie man sieht, schwankt die atmosphärische CO2-Konzentration mit der Zeit und dem Ort. Dies ist in erster Linie auf stark schwankende natürliche Quellen und Senken zurückzuführen, insbesondere auf Pflanzen. Während der Wachstumsphase im Frühling und im Sommer nehmen Pflanzen mittels Photosynthese grosse Mengen CO2 aus der Atmosphäre auf. Durch Atmung geben Pflanzen zum Beispiel durch Zersetzung herabgefallener Blätter geben Pflanzen CO2 wieder an die Atmosphäre ab, insbesondere im Herbst und im Winter. Dadurch schwankt die atmosphärische CO2-Konzentration stark mit den Jahreszeiten. Wichtige anthropogene Quellen des CO2 sind Förderung, Transport und Verbrennung fossiler Brennstoffe wie Öl-, Gas und Kohle. Die hier gezeigten Daten basieren auf der Auswertung von Strahlungsmessungen des amerikanischen OCO-2 Satelliten durch die Universität Bremen im Rahmes des ESA Projekts GHG-CCI (https://climate.esa.int/en/projects/ghgs/). Dargestellt ist das vertikal gemittelte CO2-Mischungsverhältnis in ppm (parts per million). Ist dieser Wert zum Beispiel 400 ppm an einem bestimmten Ort, so enthält die Luft über diesem Ort 400 CO2-Moleküle pro eine Millionen Luftmoleküle (Mittelwert über die ganze Atmosphäre, also vom Erdboden bis zum Weltraum).

**Comment by Immo-Be** [comment]
@annikabock did you get an answer how this should look like?

**Comment by andreashelms** [comment]
@annikabock @pmast We created a new layer for this dataset by rasterizing the input data and then transforming it into tiles using the current pipeline. Is this something that needs to be approved by ESA or how should we proceed with this?

https://storage.googleapis.com/esa-cfs-versions/web/develop/index.html#/?globe=SI45.50I-0.45I19014914I0.00I1583107200000I0Iriver_discharge.water_levelI
