### ISSUE TITLE
legend

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#356]
Investigate how we can easily realise this.

- image
- only min/max values
- allow to show unit with values
- option for third value e.g. zero for temperature

![image](https://user-images.githubusercontent.com/2733607/84639260-6baf6280-aef8-11ea-9bd4-4b6d9b822e51.png)

**Comment by pmast** [comment]
Thus might be an idea, either for export or dynamic creation:

https://codepen.io/pmast/pen/zYrbNGE

**Comment by pwambach** [comment]
Nice, will try that to generate static images
