### ISSUE TITLE
Prepare for additional languages:

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#382]
- French (FR)
- Spanish (ES, provided by @natastro)
- Dutch (NL, provided by @pmast )

The UI will be translated first.
Content will be translated later.
English should be the default for content if a language is not available.

**Comment by natastro** [comment]
Hello! Happy to help with Spanish translations if needed.

**Comment by pmast** [comment]
That's awesome @natastro! We will ping your once we are ready to go, give us another week or two.
