### ISSUE TITLE
spreadsheet mapper

### ISSUE THREAD

**Issue by JuJuPlath** [ubilabs/esa-climate-from-space#39]
0. get version number from package.json on github
1a. allow to upload excel file
1b. set story ID (get from storage)
3. convert to excel file to story json
4. upload json to storage
5. add a script to download live version in to local repo
6. add command prompt to prevent overwrite from local repo

Example spreadsheet: https://docs.google.com/spreadsheets/d/1kL8UYm5oFuKnN97hvPVp9Oj6YQ2q6CZxo_wCr9Qs5sQ/edit#gid=0

**Comment by pmast** [comment]
https://docs.google.com/spreadsheets/d/1kL8UYm5oFuKnN97hvPVp9Oj6YQ2q6CZxo_wCr9Qs5sQ/edit#gid=0
