### ISSUE TITLE
Add translations for new languages

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#405]
UI:
- [x] French: https://github.com/ubilabs/esa-climate-from-space/blob/develop/i18n/fr.json
- [x] Dutch: https://github.com/ubilabs/esa-climate-from-space/blob/develop/i18n/nl.json 
- [x] Spanish: https://github.com/ubilabs/esa-climate-from-space/blob/develop/i18n/es.json

Dataset and Story names will come later

**Comment by pmast** [comment]
@natastro feel free to fill in the Spanish part and place a PR. Let us know if you need any help

**Comment by natastro** [comment]
Thank you @pmast ! I'll begin working on this

**Comment by natastro** [comment]
Hi @pmast ! I have some quick questions while working on this:

1. `"play": "Play",` : there are a couple of translations for this. Is this as in playing a game (digital, sports) or playing audio/video?
2. `"storiesSelected": "{numberSelected, number} {numberSelected, plural, one {Story} other {Stories}} selected",` : some of these cannot be translated. Whatever is part of the code like `numberSelected` for example, would need to stay the same. Can you advise which words will be translated for this?

After this I should be able to send the PR! Thank you!

**Comment by pmast** [comment]
Hei @natastro the play refers to playing a slide deck so it is more of the audio/video category.

And for item 2: I think this is some sort of conditional for a single item or multiple item. @pwambach could probably give some background.

**Comment by natastro** [comment]
Thank you @pmast !

+ @pwambach 
I made an attempt on guessing what's used as code and translated what isn't. The translated words are in bold, see below:
"storiesSelected": "{numberSelected, number} {numberSelected, **plural, un** {Story} **otras** {Stories}} **seleccionadas**",

**Comment by pwambach** [comment]
Hi @natastro,

thanks for your help with the translations!

The message syntax is based on this format https://formatjs.io/docs/icu-syntax/#plural-format
The parts to translate are the bold ones:

> "storiesSelected": "{numberSelected, number} {numberSelected, plural, one {**Story**} other {**Stories**}} **selected**"

The final sentence in this case would be: "5 Stories selected" or "1 Story selected"

`one` and `other` in this case are the categories that decide which word is chosen: `Story` or `Stories`
