### ISSUE TITLE
Dataset: Aerosols

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#406]
- [ ] update form new dataset
- [x] change unit to `AOD550`
- [x] the colors in the original data looks darker than what we have now

Try this scale:
```
1 184 101 9 255
0 184 101 9 0
```

```
[
  [1, 184, 101, 9, 255],
  [0, 184, 101, 9, 0]
];
```

![image](https://user-images.githubusercontent.com/2733607/90109049-7f861200-dd4b-11ea-9891-133f22dfcd34.png)

If not debug later.

![image](https://user-images.githubusercontent.com/2733607/88190390-8339e380-cc3a-11ea-875f-e6b17aa4964f.png)

**Comment by pmast** [comment]
Latest version of the data:
Aerosol: /neodc/esacci/aerosol/data/AATSR_SU/L3/v4.3/MONTHLY

**Comment by pwambach** [comment]
Updated to 4.3
