### ISSUE TITLE
Datasets: About Page Style

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#424]
Adjust styling
- [x] the bold style has been adjusted to make the enumeration of properties at the end work better. See aerosols as an example.
- [x] the accent color is green
- [x] I am not sure about spacing

https://www.figma.com/file/0vDR8nc0sp2xLG7b4X8mzG/ESA-Design?node-id=1165%3A0

**Comment by KatvonRivia** [comment]
- bold font needs to be set in the markdown
