### ISSUE TITLE
ESA: application icon

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#455]
Create an application icon for the standalone application.

Das Icon sollte eine PNG Datei sein, 512x512px groß.

**Comment by pwambach** [comment]
I just saw we have the favicon as an svg? I guess we can just use this with 512 px!?
[favicon.svg.zip](https://github.com/ubilabs/esa-climate-from-space/files/5055174/favicon.svg.zip)

**Comment by pmast** [comment]
That is fine with me!
Definitely better than the Electron default icon:

![image](https://user-images.githubusercontent.com/2733607/89879143-ca285280-dbc2-11ea-8c0a-84b530d11238.png)


Also this is also spacey…

I just saw, that the Electron icon has a little drop shadow.

**Comment by pmast** [comment]
https://www.esa.int/esalogo/

**Comment by elenamuxui** [comment]
I made three variants: without shadow, with 15% shadow and with 25% shadow. 

[ESA_FAV.zip](https://github.com/ubilabs/esa-climate-from-space/files/5068940/ESA_FAV.zip)
