### ISSUE TITLE
ESA stories: change body background to black?

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#460]
Would it work if we change the background of the body part in the stories to black? That would make embedding videos and images nicer.

![image](https://user-images.githubusercontent.com/2733607/89907795-649d8b80-dbed-11ea-8d59-8773b55fc584.png)

The greyish color comes form the Toolbox, another ESA tool that we should somehow relate to:

![image](https://user-images.githubusercontent.com/2733607/89911996-59992a00-dbf2-11ea-814e-b2cfa08bbca0.png)

**Comment by elenamuxui** [comment]
I think the idea is generally very good. But we have to be careful that the pictures and videos look tidy. The pictures fonts have a differently size and make the application a bit messy. If it looks like a picture it's okay, but not so good as part of an application.

<img width="946" alt="Bildschirmfoto 2020-08-12 um 09 29 39" src="https://user-images.githubusercontent.com/63637901/89987589-990d5800-dc7e-11ea-89fe-6cea6a8f24bd.png">
<img width="1979" alt="Bildschirmfoto 2020-08-12 um 09 07 09" src="https://user-images.githubusercontent.com/63637901/89986960-95c59c80-dc7d-11ea-8537-12993ea2f250.png">

**Comment by pmast** [comment]
Ok, let's do this: https://github.com/ubilabs/esa-climate-from-space/issues/463

I will try do add some attention to the issue with the images. However they come from external sources and it will be difficult to get them updated and match our style.
