### ISSUE TITLE
Error capturing

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#467]
Capture errors that happen during runtime.
We have to report quarterly which errors happen.

Use User-Tracking platform to also store error events.

Catch global error events of app and send to tracking platform.

We do probably need user consent for sending this information.

**Comment by pmast** [comment]
I have created an google analytics account:

**Tracking ID:** `UA-175641964-1`

Global Site Tag (gtag.js):
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-175641964-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-175641964-1');
</script>
```

**Comment by pmast** [comment]
On how to track errors with google analytics or tag manager:

https://developers.google.com/analytics/devguides/collection/analyticsjs/exceptions
https://support.google.com/tagmanager/answer/7679411

**Comment by pmast** [comment]
Capturing errors globally:

https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror

**Comment by mrMetalWood** [comment]
https://matomo.org/faq/how-to/how-do-i-enable-basic-javascript-error-tracking-and-reporting-in-matomo-browser-console-error-messages/
