### ISSUE TITLE
User tracking

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#472]
~~The website uses Google Analytics.~~

ESA does not approve Google analytics.
ESA has to provide a new solution.
We need user consent for tracking.

Track:
- [x] selected datasets
- [x] selected stories
  - [x] maybe also progress in stories?
- [x] selected compare mode
- [x] social sharing

**Comment by aemkei** [comment]
https://www.npmjs.com/package/@datapunt/matomo-tracker-react

**Comment by aemkei** [comment]
Default configuration:

```js
var _paq = window._paq || [];
/* tracker methods like "setCustomDimension" should be called before "trackPageView" */
_paq.push(['trackPageView']);
_paq.push(['enableLinkTracking']);
(function() {
var u="https://matomo-ext.esa.int/";
_paq.push(['setTrackerUrl', u+'matomo.php']);
_paq.push(['setSiteId', '4']);
var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
})();
```

But as we use the NPM module there might be a shorter syntax.

**Comment by aemkei** [comment]
More information about the tracking here: https://developer.matomo.org/guides/tracking-javascript-guide

**Comment by aemkei** [comment]
Please Note that we have to display a consent screen before tracking the client:

https://developer.matomo.org/guides/tracking-consent

**Comment by aemkei** [comment]
UPDATE: I put this (partially) on hold. Please do not use the credentials above because this would report the stats into another analytics project. 

Email from mmediait.com:

> Sorry, but you can not reuse the javascript track because it has a reference for that site, and as I guess from your needs, administrators are completely different from climate.esa.int , right? Also you need to have separate reports. If you use the same JS, you are merging the analytics from climate.esa.int. So please, do not use that JS, even for testing , because also the request from your service is pending to be clarified.
> We have still pending to clarify from Charles in conversition with Paul Fisher if you need another request and how to handle it. Also, remember that you need to have an ADFS account to access all the reports. So, even if you integrate with the service, you need ESA Corporate account to access the reports. This is a strong requirement to start using the platform.



But can we already start to implement the behavior for the consent screen and the page tracking?

**Comment by aemkei** [comment]
We got access!

```js
var _paq = window._paq || [];
/* tracker methods like "setCustomDimension" should be called before "trackPageView" */
_paq.push(['trackPageView']);
_paq.push(['enableLinkTracking']);
(function() {
var u="https://matomo-ext.esa.int/";
_paq.push(['setTrackerUrl', u+'matomo.php']);
_paq.push(['setSiteId', '6']);
var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
})();
```
