### ISSUE TITLE
Story selector: set background image to cover

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#489]
Ensure that the background image always fills the background.

![image](https://user-images.githubusercontent.com/2733607/90643635-16633a80-e234-11ea-9e3c-aee8cc88e1a4.png)

**Comment by KatvonRivia** [comment]
I fell into this trap as well. 😂 It is set to cover but the actual image has that black border: https://storage.googleapis.com/esa-cfs-storage/0.7.0/stories/story-16/assets/sst_large_18.jpg

**Comment by pmast** [comment]
Here is an image that should work:

![image](https://user-images.githubusercontent.com/2733607/90732421-5aede500-e2cb-11ea-93c1-236934f7ca4f.png)

Could you add this as an extra asset for the story tile?!
The original image is used in the story somewhere else.
