### ISSUE TITLE
Story pins

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#500]
- [ ] update to a pure circular pin
- [ ] move the anchor point to the center of the pin so that the pin always sticks to the same location when rotating the globe. The anchor now seems to be the top eft corner.

![image](https://user-images.githubusercontent.com/2733607/90879873-e0df5e00-e3a7-11ea-97b2-d45121410f15.png)
![image](https://user-images.githubusercontent.com/2733607/90879895-ea68c600-e3a7-11ea-89a4-169d4660c4c7.png)

**Comment by pmast** [comment]
@KatvonRivia great, how does the JSON structure look like and how would this be inserted in a spreadsheet?

**Comment by KatvonRivia** [comment]
This PR was for the markers in data mode.

But the ones for the globe in the stories look like this now:

```
"markers": [
        {"position": [10, 50], "title": "test marker title"},
        {"position": [50, 10], "title": "test marker title"}
      ],
```

I will check with @pwambach on how to add it to the spreadsheet.
