### ISSUE TITLE
Datasets: Glaciers

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#507]
- add the high resolution raster as glacier overlay:

![glaciers_large](https://user-images.githubusercontent.com/2733607/130434234-dffc9a0d-702f-47bb-bb22-184939073b4a.png)

~~- [ ] get high resolution raster export~~

**Comment by pmast** [comment]
Tippecano seems to be able to handle different map projections:

https://github.com/mapbox/tippecanoe/issues/422#issuecomment-308521148

Might be an idea to try vector tiles one day…

**Comment by pmast** [comment]
Reduced file with image optim (590% file size savings):

![glaciers-reduced](https://user-images.githubusercontent.com/2733607/130598286-c977743d-a25f-4f6a-8ae7-134250b6e1b5.png)

**Comment by pwambach** [comment]
nice 590%! 😄

**Comment by pmast** [comment]
🏋️ 🔨 🥞

**Comment by pwambach** [comment]
Added the layer but description is missing, can you add it into the PR @pmast? https://github.com/ubilabs/esa-climate-from-space/pull/964
