### ISSUE TITLE
Dataset: Greenhouse gases

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#508]
- [x] update to v4.2 data (ranging to  december 2019) [get data here]
(https://drive.google.com/drive/folders/1OoiTRqfikOpm72fRs5FwflPfb9o6hcX4)
  - variables are: `xch4` and `xco2`
- [x] export CO2 data with correct color scheme (see bellow)
- [x] export CH4 data with correct color scheme (see bellow)
~~- [ ] get data from copernicus~~

**Comment by pmast** [comment]
I checked back email conversations and data stores. It seems the Obs4Mibs data we have is the best available. Unfortunately.

**Comment by pmast** [comment]
CO2:
![image](https://user-images.githubusercontent.com/2733607/92893854-5922c780-f41a-11ea-8e38-6541b0da8c3b.png)
```
400 168 35 21
394.17 255 109 43
388.33 250 227 66
376.67 0 213 252
365 0 44 153
```

**Comment by pmast** [comment]
CH4:
![image](https://user-images.githubusercontent.com/2733607/92894020-853e4880-f41a-11ea-8743-20254c04a56b.png)

```
1825 183 40 24
1812 240 60 40
1807 255 100 40
1785 255 220 65
1766 233 233 80
1755 180 245 127
1731 60 240 220
1717 0 200 255
1664 0 50 170
1650 0 44 153
```

**Comment by pwambach** [comment]
Output images had only one color. After checking the min/max values I adjusted the colors maps to 
```
0.000001825 183 40 24
0.000001812 240 60 40
0.000001807 255 100 40
0.000001785 255 220 65
0.000001766 233 233 80
0.000001755 180 245 127
0.000001731 60 240 220
0.000001717 0 200 255
0.000001664 0 50 170
0.000001650 0 44 153
nv 0 0 0 0
```

and

```
0.000400 168 35 21
0.00039417 255 109 43
0.00038833 250 227 66
0.00037667 0 213 252
0.000365 0 44 153
nv 0 0 0 0
```

**Comment by pmast** [comment]
:+1:

**Comment by pmast** [comment]
@lassescheele, could you prepare the latest version of the greenhouses gases for us?

You already had done that earlier.

https://drive.google.com/drive/folders/1OoiTRqfikOpm72fRs5FwflPfb9o6hcX4

**Comment by lassescheele** [comment]
It seems that the new data (v4.2) has a resolution of only 5° x 5°.
@pmast is that as expected?

**Comment by pwambach** [comment]
I tested the new xco2 files and somehow the resolution seems to be less than 180x90 pixels.
The new xco2:
![xco2](https://user-images.githubusercontent.com/1611635/93433452-1b64e980-f8c7-11ea-8dc6-a679a0f318da.png)

and the old xch4:
![xch4](https://user-images.githubusercontent.com/1611635/93433471-20299d80-f8c7-11ea-9dc2-df2179f03b4f.png)

Both source files (the tifs from Lasse) have a resolution of 180x90 but the new xco2 seems to have a lower "internal" resolution. The question is if it's like that in the original source files or if comes from our processing.

**Comment by pmast** [comment]
Hm that's not nice.

The portal where I have downloaded the data indeed states that it is 5º x 5º resolution which would be 72x36 pixel.
I have to trace back where I got the older version from. And talk to the science team directly.

**Comment by pmast** [comment]
I got in contact with the science team:
1. they like what we have
2. there will be a 2 degree version coming for the latest data, just not yet.

--> in the mean time we should add the 5 degree version of CH4 as well.

I prefer the 5 degree version above the 2 degree version because it runs longer.
