### ISSUE TITLE
Dataset: Sea State

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#512]
- [x] limit min/max values while exporting
- [x] Adjust values on legend to reflect the boundaries of our color scale:
  - `0m`
  - `> 6m`
- [x] use the reverse matplotlip The blues data scale:
```
0  8 48 108
2 54 134 192
4 171 207 229
6 247 251 255
```

**Comment by pwambach** [comment]
already in use. we made our own version with a bit more steps but same values:

```
6.0 247 251 255 255
5.4 227 238 248 255
4.8 207 225 242 255
4.2 182 212 233 255
3.6 147 196 222 255
3.0 106 173 213 255
2.4 74 151 201 255
1.8 45 125 187 255
1.2 23 100 171 255
0.6 8 73 145 255
0.0 8 48 107 255
nv 0 0 0 0

```
