### ISSUE TITLE
Data Viewer: add semi transparent background to bottom controls

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#523]
For better readability when zoomed in, add a semi transparent back ground behind footer control elements.

See here for designs:
https://www.figma.com/file/0vDR8nc0sp2xLG7b4X8mzG/ESA-Design?node-id=1136%3A32523

![image](https://user-images.githubusercontent.com/2733607/91192948-d9e18400-e6f6-11ea-9ba0-36d0b1b4b3fe.png)

**Comment by KatvonRivia** [comment]
Should I also move the data-set-info to the top, @pmast ? Currently its at the bottom below the slider.

**Comment by pmast** [comment]
I would leave it like it is.

Having the dataset names on top isn't a good solution either. We might ask Elena for another look, one day.
