### ISSUE TITLE
Prepare production deployment

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#540]
Create a separate deployment for the new domain that the application will run under:
- [x] create new bucket: `cfs.climate.esa.int`
- [x] create separate deployment for this bucket, no subfolders, index.html should be in root, with cashing enabled?!
- [x] setup loadbalancer for IP

**Comment by pmast** [comment]
Interesting:

![image](https://user-images.githubusercontent.com/2733607/91670786-e4e64b00-eb20-11ea-9356-1bb6f28df4a4.png)

**Comment by pmast** [comment]
Bucket created:

![image](https://user-images.githubusercontent.com/2733607/91830587-41418b80-ec43-11ea-87df-f3970eccb519.png)

**Comment by pmast** [comment]
External IP address: 34.98.126.100:80

**Comment by pwambach** [comment]
Added a `live` branch with auto deployment. No extra cache header set so the default 3600s caching applies.
