### ISSUE TITLE
Datasets: Soil Moisture

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#554]
- [x] add new monthly aggregates
- [x] use monthly_mean first
- [ ] also export anomalies when everything is smooth. use sea level anomalies color scale

Data sources: https://owncloud.tuwien.ac.at/index.php/s/bY8j2kBgZlkqFYC

All time steps are in one file.
The file only contains one variable.
The file contains one band for each time step.

Output from `gdalinfo ESA_CCI_SM_v04.7_COMBINED_Anomalies.nc`:

![image](https://user-images.githubusercontent.com/2733607/91766871-88943180-ebdb-11ea-9033-6dd2a4217e96.png)

Each band has a field `NETCDF_DIM_time` which apparently gives the days since  epoch:
`time#units=days since 1970-01-01T00:00:00+00:00`

`gdalinfo -json ESA_CCI_SM_v04.7_COMBINED_Anomalies.nc` gives the information on the band as json. This should make it possible to script the export and date assignment.

This works for the image export:
```
gdal_translate \
    -b 1 \
    ESA_CCI_SM_v04.7_COMBINED_Anomalies.nc \
    SM.tif
```

**Comment by pmast** [comment]
Gdal is crazy…

**Comment by pwambach** [comment]
😄  yes it is!
I splitted the file with xarray in multiple .nc files with one timestamp per file. This way we can use the normal pipeline to generate the images.

**Comment by pmast** [comment]
Perfect!
