### ISSUE TITLE
Time Slider: gaps in ticks are not shown

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#557]
The sea ice layer has a gap from October 2011 to August 2012.
- [x] The time slider track should show a gap where there is no data.
- [x] also the data set seems to change when the handle is moved through the gap

**Comment by pwambach** [comment]
Just saw this ticket... We don't really know when there is a gap because we have just timestamps. The timstamps do not always have the same distance so we would have to "guess" where there is a gap.

**Comment by pmast** [comment]
Yes, but I thought the ticks are placed by time?! Then a wider gap should be visible?!

**Comment by mrMetalWood** [comment]
Did somebody do anything with this issue? Looks fine to me.

![Bildschirmfoto 2020-09-03 um 09 30 34](https://user-images.githubusercontent.com/2902795/92084867-48de6d00-edc8-11ea-8292-1d35ece53c05.png)

The timeslider doesn't show the time of the handle position but rather the date of the currently shown tiles. Thats why it appears to be jumping when you scroll through.

**Comment by pmast** [comment]
Ah right now I see it… 👍 

We might need to add some more contrast to the ticks.
But I still have the impression that the dataset changes when moving through the gap.
