### ISSUE TITLE
Basemaps: update blue basemap

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#606]
New file:
https://drive.google.com/file/d/1ZKV7S11nJt5GGQI9Yn1sFvQsiF8pL3_U/view?usp=sharing

From Philip:
> The land was accidentally brightened when we enlarged it from the old software. We noticed we had reduced contrast when we made the graphics files for the Snow data. This darker land will give better contrast for Snow and Cloud, and should be fine for Sea Ice, which is the other dataset that uses it.

**Comment by pwambach** [comment]
updated
