### ISSUE TITLE
Stories: full screen images

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#645]
- [ ] semi transparent background should cover back arrow

**Comment by KatvonRivia** [comment]
What exactly is your intension here? I think it would we weird to hide the back button, when all the other controls are visible. Also the transparent background is not covering the whole screen.

![image](https://user-images.githubusercontent.com/45818654/94136749-ac0e6d00-fe65-11ea-8c54-86bae34fc56a.png)

**Comment by pmast** [comment]
Hm, you are probably right. Let's leave it like it is.
