### ISSUE TITLE
2D: ensure that initially the complete dataset is visible.

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#650]
Probably needs to adjust the zoom constraints.

And this might be window size dependent?!

**Comment by mrMetalWood** [comment]
Apparently it has nothing to do with the zoom constraints and I don't now right now how to prevent the little 'jump in' when changing to 2D and the 'jump out' when changing to 3D

**Comment by KatvonRivia** [comment]
@sadrda checked it out on cesium sandcastles and it shows the same behaviour: 

https://sandcastle.cesium.com/#c=bY69bsMwDIRfRdAkA4HkZK1sFEjHAhkSdNKiyGxDRD+GRDlIn76226Fow+2O3x052cwmhBtk1rEIN7aHgjXIt9UThrtV71MkixGy4c2TiQXohAFSJSGarv9pkMVBBBlSHi+ntHsR22bDdm3bNnzDdaG7h95Ets4zhjFlYjV7IaUiCKO3BEWdq7sCSVfKcmhBtfod1QNODIfuwWfMeVvKvHmv3h/xEwzvtZr5f1Gf7IDx4zBB9va+YJdt//ptSim1muXjJKXkzzb/af4C

**Comment by pmast** [comment]
We leave it for now.
