### ISSUE TITLE
Stange padding in stories

### ISSUE THREAD

**Issue by aemkei** [ubilabs/esa-climate-from-space#671]
I see a strange padding when skipping through the story: https://storage.googleapis.com/esa-cfs-versions/web/develop/index.html#/stories/story-26/3?globe=SI12.67I41.83I25003000.00I360.00I-90.00I0.00I0.00I0.00II

![Oct-07-2020 22-00-34](https://user-images.githubusercontent.com/1521/95381564-9dee3100-08e8-11eb-9223-46f4df2e3b7d.gif)

**Comment by aemkei** [comment]
Looks like this is caused by the `::-webkit-scrollbar` style. 

Was there a reason to use this instead of the floating scollbar?

**Comment by KatvonRivia** [comment]
We used `::-webkit-scrollbar` to style the scrollbar. It also needs a preset width, thats why we see the padding jump when there is no scollable content.
