### ISSUE TITLE
Simple GCP storage logging (to see how many times index.html was requested)

### ISSUE THREAD

**Issue by aemkei** [ubilabs/esa-climate-from-space#676]
It might be that we do not get the tracking code running in time for the conference. Better have a plan B and use stats from Cloud Storage.

**Comment by aemkei** [comment]
https://cloud.google.com/storage/docs/access-logs#delivery

**Comment by mrMetalWood** [comment]
I enabled the logging for the live bucket. Will check later what gets logged there.

**Comment by mrMetalWood** [comment]
Logs are here. Not exactly sure how to read them, but you can see requests to index.html
https://console.cloud.google.com/storage/browser/cfs-live-logs?project=esa-climate-from-space&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false
