### ISSUE TITLE
Issue with link to time (see email from PE)

### ISSUE THREAD

**Issue by KatvonRivia** [ubilabs/esa-climate-from-space#696]
I tried to update the SST/OC comparison globe on Heat Pumps screen 5, to show a date that has less data dropout (gaps) in the OC:

https://storage.googleapis.com/esa-cfs-versions/web/develop/index.html#/stories/story-16/4?globe=SI-30.74I23.32I15145050.29I360.00I-89.86I0.00I368193600000.00I0.00Isst.analysed_sstIoc.chlor_a

I tried pasting a link from the data viewer with the date I wanted (1 Feb 2005). When I open the link in another window, it shows the correct location, but takes me straight to the final OC date 2019-11-30 (which is beyond the end of the SST).

Here is the link I grabbed:

https://storage.googleapis.com/esa-cfs-versions/web/develop/index.html#/?globe=SI-66.26I-20.51I11774250.96I360.00I-89.87I0.00I1109505600000.00I0.00Isst.analysed_sstIoc.chlor_a

To investigate I worked out the date 2005-02-01 00:00:00 in milliseconds (!) as 1107244800000
(using https://currentmillis.com)

The time shown in the link is close to that. Certainly closer than 2019-11-30 = 1575100800000.

So something going wrong with the time parameter? I’m assuming it is unix time milliseconds?

Of course, this would be easier to investigate if the parameters were specified as human dates rather than milliseconds...

**Comment by aemkei** [comment]
Looks like dragging the time slider updates the URL but updating the URL won't sync the time slider.

cc @mrMetalWood
