### ISSUE TITLE
Refactor asset pipeline. Currently it is hard to keep track of changes.

### ISSUE THREAD

**Issue by aemkei** [ubilabs/esa-climate-from-space#724]
I guess we need to rework and clean up the existing folders before continuing here.  It is super hard to keep track of changes in ZIPs and we definitely should switch to a better system.  There are also files with different naming conventions (hyphen vs underscore), file types (png vs jpg) and suffix (eg "-old"). Also some files are huge (eg. story15_07 is a 3.3 MB JPEG) and will take some time to load.

Feedback from PV:

The folders are being used by the Education workpackage as well as by CfS. They are sometimes using a different selection of images, and may use them in print as well as digital, so I’ve left images as full-size and kept files that we are no longer using, rather than delete them. We also have some test video files there, although CfS is taking them from YouTube. So, yes, the folders look a little messy.

If we can get a cleaner process, where images are uploaded direct to your web server, we can make sure that you also get cleaner folders, with only the CfS content. Now the app is published we have some time to think about this.

**Comment by pmast** [comment]
We will solve this by this: https://github.com/ubilabs/esa-climate-from-space/issues/737
