### ISSUE TITLE
Story timeslider shows wrong time (Mail from PE)

### ISSUE THREAD

**Issue by KatvonRivia** [ubilabs/esa-climate-from-space#733]
Mail from PE:

> When I try to call a different date and viewpoint (1 Feb 2005 or 2006, S America), ...(*it reverts to the start of the SST sequence (Sept 1 1981)* PR: #732)... Then when I refresh the browser, it reverts to May 1 200/April 30 2002, both looking at the N Atlantic. [...]
> 
> When I take the link from my excel file and paste it into a browser, it works fine. But when I upload the excel file into the software, it doesn’t (as described above). Here is the link I am using:
> 
> https://storage.googleapis.com/esa-cfs-versions/web/develop/index.html#/?globe=SI-60.11I-19.14I10614832.84I360.00I-89.83I0.00I1238414400000.00I0.00Isst.analysed_sstIoc.chlor_a
> 

So apparently he was adding a link with a 2009 timestamp and after he uploaded it via story mapper, the story slide was showing a wrong globe position and timestamp (2002).

**Comment by pmast** [comment]
Solution might be to update this file: https://github.com/ubilabs/esa-climate-story-mapper/blob/master/src/third-party/parse-globe-parameters.ts#L8
