### ISSUE TITLE
Update story mapper

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#735]
- [x] update to new URL scheme
   - [ ] ~make it use the URL decoder from main repo~ not working
    - [x] update spreadsheets
Should solve this as well: https://github.com/ubilabs/esa-climate-from-space/issues/733

**Comment by pwambach** [comment]
Reusing the original function is not going to work. 
Cloud functions can not install the repo directly from github and the function itself is not a 1 to 1 copy. There are some small differences in the function parameter and return value.

I updated the function manually to the new version.

**Comment by pmast** [comment]
Perfect, would it help to add a comment about the reuse of this function?
