### ISSUE TITLE
Dataset: Greenhouse Gases

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#744]
We have received new 2deg data: https://drive.google.com/drive/folders/1cpZk_LoG06Qnjz9LSoo7zj6thJ5AxQLW
- [x] prepare the data for ingestion into CfS
  - CO2
  - CH4
- [x] ingest the new data into CfS
  - CO2
  - CH4

**Comment by lassescheele** [comment]
The prepared 2deg data can be found here: https://drive.google.com/drive/folders/1syO5YFE-Hw1k3KACntpdX1hy5ZO4YKMi?usp=sharing.
The corresponding files are `xco2_2x2.zip` and `xch4_2x2.zip`.

**Comment by pwambach** [comment]
Updated files in v0.10.4
https://storage.googleapis.com/esa-cfs-versions/web/develop/index.html#/?globe=SI29.62I1.37I20699288.65I360.00I-89.79I0.00I1251936000000.00I0.00Igreenhouse.xco2Igreenhouse.xch4
