### ISSUE TITLE
Create a version for Museon

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#765]
Create a stripped down version of the application for Museon to be used in their permanent museum exhibition. The version should only feature the story content
- [x] set up a separat branch for that version
- [x] remove aces to the data layers
- [x] remove access to the settings menu
- [x] remove access to sharing menu
- [x] hide globe navigation elements
- [x] make separate deployment
- [x] use content from live deployment

**Comment by KatvonRivia** [comment]
https://storage.googleapis.com/esa-cfs-versions/web/museon/index.html#/

**Comment by pmast** [comment]
Ah nice!

I still get a bunch of errors and no globe:

![image](https://user-images.githubusercontent.com/2733607/101142568-12f29400-3616-11eb-8366-772c8692e40b.png)
