### ISSUE TITLE
Apply tag filter to globe view

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#823]
- [x] also apply the tag filter to the globe view
- [x] indicate in the UI that the current globe view is filtered
- [x] give the option to remove the filter
- [x] do not give the option to set new filters in this view

**Comment by pmast** [comment]
An idea:
![image](https://user-images.githubusercontent.com/2733607/104564057-bd64ca80-564a-11eb-8fd0-d50ebab96ef2.png)

**Comment by elenamuxui** [comment]
<img width="685" alt="Bildschirmfoto 2021-01-14 um 16 29 20" src="https://user-images.githubusercontent.com/63637901/104611916-eb1b3500-5685-11eb-816b-ad1081a59475.png">
