### ISSUE TITLE
Stories: data view

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#839]
The captions in data view should be more prominent currently the time slider is to prominent.

**Comment by pmast** [comment]
Screenshot of how it looks currently:
![image](https://user-images.githubusercontent.com/2733607/109436328-3ebbc500-7a1f-11eb-8d23-bde41425faaf.png)

**Comment by elenamuxui** [comment]
<img width="601" alt="Bildschirmfoto 2021-03-05 um 08 02 07" src="https://user-images.githubusercontent.com/63637901/110079192-1a4a4a80-7d89-11eb-996e-40548bf336ee.png">
<img width="598" alt="Bildschirmfoto 2021-03-05 um 08 02 00" src="https://user-images.githubusercontent.com/63637901/110079200-1c140e00-7d89-11eb-972b-78977944fda0.png">
