### ISSUE TITLE
Navigation from CfS back to ESA Climate Office website

### ISSUE THREAD

**Issue by annikabock** [ubilabs/esa-climate-from-space#879]
There's a lack of navigation from CfS to the ESA Climate Office website at the top of pages. Also lack of ESA logo in stories mode. This is particularly a problem for the stories mode if users are directed to a particular page or image via a shared link: there's no way of telling that the page they land on is related to ESA as there's no logo on the page or navigation back to the main site. It could be remedied by adding the ESA logo and making it a live link in the top dark grey bar. This was flagged as a problem by Paul Fisher who is thinking about particular user promotion from particular pages of CfS.

**Comment by elenamuxui** [comment]
![Uploading Bildschirmfoto 2021-03-25 um 09.26.09.png…]()

**Comment by elenamuxui** [comment]
<img width="876" alt="Bildschirmfoto 2021-03-25 um 09 26 09" src="https://user-images.githubusercontent.com/63637901/112442605-4d5e7900-8d4c-11eb-91c8-c8a25bacf907.png">

**Comment by elenamuxui** [comment]
<img width="464" alt="Bildschirmfoto 2021-03-25 um 09 29 43" src="https://user-images.githubusercontent.com/63637901/112442922-a3cbb780-8d4c-11eb-85ae-170a98471e7f.png">

**Comment by annikabock** [comment]
ah maybe there was a misunderstanding in the last image with the linking on the main page. The link that is missing should go to
https://climate.esa.int/en/
To ESA Climate Office not to Climate from Space. But we need to keep the line/title of the page. 
Or maybe this is what you mean.. hmm but normally Logos on a page let the user "return" to the main page and not lead to another page. Is there any other idea maybe?

**Comment by elenamuxui** [comment]
<img width="863" alt="Bildschirmfoto 2021-03-31 um 08 40 25" src="https://user-images.githubusercontent.com/63637901/113105225-a709ec00-9201-11eb-848e-488e8c4f1fed.png">
![Uploading Bildschirmfoto 2021-03-31 um 08.40.11.png…]()

**Comment by elenamuxui** [comment]
<img width="858" alt="Bildschirmfoto 2021-03-31 um 11 26 41" src="https://user-images.githubusercontent.com/63637901/113122519-0113ad00-9214-11eb-87b6-7ae5f8640e59.png">
<img width="735" alt="Bildschirmfoto 2021-03-31 um 11 28 05" src="https://user-images.githubusercontent.com/63637901/113122711-2bfe0100-9214-11eb-8a84-ad060d2188ea.png">

**Comment by annikabock** [comment]
@elenamuxui can you make this two things for mobile as well please?

**Comment by elenamuxui** [comment]
<img width="711" alt="Bildschirmfoto 2021-04-07 um 11 42 18" src="https://user-images.githubusercontent.com/63637901/113845975-514fb980-9796-11eb-98cd-601fbbce5edf.png">

**Comment by elenamuxui** [comment]
<img width="426" alt="Bildschirmfoto 2021-04-07 um 11 54 08" src="https://user-images.githubusercontent.com/63637901/113847640-f919b700-9797-11eb-9f83-6e09bb5e6e56.png">
