### ISSUE TITLE
Fire: legend colors do not match data set

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#882]
There is no yellow in the legend:

![image](https://user-images.githubusercontent.com/2733607/113046879-e3f1c680-91a0-11eb-8e52-379325d040db.png)

**Comment by pwambach** [comment]
https://github.com/ubilabs/esa-climate-from-space/pull/916

I also copied the fixed image to the current live version 1.1.0

**Comment by pwambach** [comment]
https://github.com/ubilabs/esa-climate-from-space/pull/917

Adjusted the legend values. This is now the current state:
![Screenshot 2021-05-11 at 10 26 35](https://user-images.githubusercontent.com/1611635/117784109-7cb93e80-b243-11eb-90c1-35bf3e66a77b.png)

Also updated on live (1.1.0) version
