### ISSUE TITLE
Text in stories main header weird

### ISSUE THREAD

**Issue by annikabock** [ubilabs/esa-climate-from-space#912]
maybe the font size is too small or it is just positioned too high - not entirely sure but definitely not like it is put in the designs. Could you please adapt
![Screenshot_20210427-203602](https://user-images.githubusercontent.com/8329219/116356557-b6c62180-a7fb-11eb-8da1-9449959d0014.png)

**Comment by KatvonRivia** [comment]
The spacing looks weird yes, the rest is on purpose. We don't have a back button text label, we show the story title.
