### ISSUE TITLE
Investigate deepl for automated translations

### ISSUE THREAD

**Issue by annikabock** [ubilabs/esa-climate-from-space#915]
DeepL has an API for translating texts and we have commercial license
https://www.deepl.com/en/docs-api/

Please check if it is possible to
parse the spreadsheet, translate the content by each cell, write translation back to the spreadsheet (new tab) in order PE (or anybody) can go through the translations and correct here and there if needed

**Comment by pwambach** [comment]
I see two options here:

**In Excel:**
Excel doesn't have a native translation feature. There are several third plugins translation extensions but they all look kind of unusable. Excel has Office Scripts which looks like we could pick text from each cell and make requests to the deepl API with it. So I guess we could check if there are empty text fields in the non english sheets and fetch a translation for each of them. The advantage would be that this can happen inside the original excel file. The disadvantage is that we have no knowledge at all of scripting stuff in Excel and we need a valid Excel license to work with. Also I have no idea how secrets like the deepL API key are handled in these shared excel scripts. As far as I could figure it out everyone who has access to the script can read it completely.
https://docs.microsoft.com/de-de/office/dev/scripts/overview/excel

**In Googel Sheets:**
Sheets supports translations out of the box with the Google translator. The process could look like this:
The user imports the xlsx file from excel. We run a custom "Apps Scripts" script which also checks empty fields in non english sheets and translates the text. Result would have to be brought back to excel. It should also be possible to use the deepL API in sheets manually if that is a requirement. The advantage of sheets is that it looks a lot easier with the built-in translator and we are more familiar with sheets than with excel. But for both of them we need to learn some basics first. The downside here is that there is copy/paste involved.
https://developers.google.com/apps-script/overview

And please note that the translation quality varies and definitely needs manual corrections (from what I see in my experiments with the Google Translator). Fortunately it looks like that the formatting markdown parts in the text are just ignored.

Another point to note is that it's possible (depending on the changes) that the scripts need some maintenance in case of changes to the sheet structure. 

Doing the translation somewhere else (e.g. in the StoryMapper) would be easy to implement but isn't a good option in my opinion. The (corrected) translations would need to be copied back one by one from the json to the sheet. This seems like a task nobody wants to do :)

**Comment by annikabock** [comment]
defined process:

In terms of part A, the most preferred and hopefully the most straight-forward option would be the following:
- convert the Excel files into Word files using a freeware convertor (e.g., https://convertio.co/de/xls-doc/ that BC have not tested) *OR* use a script to read and write Excel into TXT/CSV using cell identificators
- merge all stories into one file, or a few files, up to 10 Mb each
- use our existing DeepL Pro license to translate that single file(s) into 4 languages --> send to reviewers
- split up and convert the translated Word file back into one Excel for each story using a freeware convertor (e.g., https://smallpdf.com/blog/word-to-excel-converter that BC have not tested) *OR* use a script to read and write TXT/CVS into Excel using the identificators from the first step so that column separation is not lost
- [UBI] use existing CfS script to convert Excel files into runtime code JSON and deploy onto CfS
